# Generated by Django 5.0.6 on 2024-07-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.FloatField(),
        ),
    ]
